global without sharing class GlobalTriggerSwitch {
    global static Boolean runOrderDetailTrigger = true;
    global static Boolean runOrderTrigger = true;
    global static Boolean runProcedureTrigger = true;
    global static Boolean runProcedureFormTrigger = true;
    global static Boolean runTerritoryTrigger = true;
    global static Boolean runAccountTrigger = true;
    global static Boolean runTerritory_HistoryTrigger = true;
    global static Boolean runAccount_AddressTrigger = true;
    global static Boolean runInvoiceTrigger = true;
    global static Boolean runInvoiceItemTrigger = true;
    global static Boolean runOrderItemDetailTrigger = true;
    global static Boolean runPriceBook2Trigger = true;
    global static Boolean runProduct2Trigger = true;
    global static Boolean runShipmentTrigger = true;
    global static Boolean runPricingQADInputTrigger = true;
    global static Boolean runOpportunityTrigger = true;
    global static Boolean runContactTrigger = true; 
    global static Boolean runUserTrigger = true;
    global static Boolean runEventTrigger = true;



}